config/routes.rb
Rails.application.routes.draw do
  root to: 'session#show'

  authpwn_session

  get 'venues' => 'venues#index'
  post 'venues/:id/add_warning' => 'venues#add_warning'

  resources :users

  get 'legal/:document' => 'legal#show', as: :legal
  get 'legal' => 'legal#show'

end

app/models/session.rb
# Virtual model for the information collected when a user signs in.
class Session
  include Authpwn::SessionModel

  # Add your extensions to the Session class here.
end

app/controllers/session_controller.rb
# Manages logging in and out of the application.
class SessionController < ApplicationController
  include Authpwn::SessionController

  # Sets up the 'session/welcome' view. No user is logged in.
  def welcome
    # You can brag about some statistics.
    @user_count = User.count
    render 'session/welcome', layout: 'web_welcome'
  end
  private :welcome

  # Sets up the 'session/home' view. A user is logged in.
  def home
    render 'session/home', layout: 'map'
  end
  private :home

  # The notification text displayed when a session authentication fails.
  def bounce_notice_text(reason)
    case reason
    when :invalid
      'Invalid e-mail or password'
    when :expired
      'Password expired. Please click "Forget password"'
    when :blocked
      'Account blocked. Please verify your e-mail address'
    end
  end

  # A user is logged in, based on a token.
  def home_with_token(token)
    respond_to do |format|
      format.html do
        case token
        when Tokens::EmailVerification
          redirect_to session_url, notice: 'E-mail address confirmed'
        when Tokens::PasswordReset
          redirect_to change_password_session_url
        # Handle other token types here.
        end
      end
      format.json do
        # Rely on default behavior.
      end
    end
  end
  private :home_with_token

  # If true, every successful login results in a SQL query that removes expired
  # session tokens from the database, to keep its size down.
  #
  # For better performance, set this to false and periodically call
  # Tokens::SessionUid.remove_expired in background thread.
  self.auto_purge_sessions = true

  # You shouldn't extend the session controller, so you can benefit from future
  # features. But, if you must, you can do it here.
end

app/views/session/forbidden.html.erb
<% if current_user %>
<p>
  Sorry, you are not allowed to see this page.
</p>
<p>
  If you think you should be able to see this page, try
  <%= link_to 'signing out', session_path, method: :delete %> and signing in as
  a different user. You are currently signed in as
  <strong><%= current_user.email %></strong>.
</p>
<% else %>
<p>
  The user will only see this if JavaScript is disabled. Ask them to
  <%= link_to 'sign in', new_session_path %>.
</p>
<script type="text/javascript">
window.location = "<%= new_session_path %>";
</script>
<% end %>

app/views/session/home.html.erb
<div id="google-maps-container"></div>
<ul id="filters-container">
  <p class="filter-container-label">Find locations with...</p>
  <p class="filter-group-label">Resources:</p>
  <li>
    <input type="checkbox" id="filter-water-switch"
        data-filter-value="water" />
    <label for="filter-water-switch">
      Water
      <%= image_tag 'water_pin.png', size: '16x16', alt: 'water' %>
    </label>
  </li>
  <li>
    <input type="checkbox" id="filter-food-switch" data-filter-value="food" />
    <label for="filter-food-switch">
      Food
      <%= image_tag 'food_pin.png', size: '16x16', alt: 'food' %>
    </label>
  </li>
  <li>
    <input type="checkbox" id="filter-heat-switch" data-filter-value="heat" />
    <label for="filter-heat-switch">
      Heat
      <%= image_tag 'heat_pin.png', size: '16x16', alt: 'heat' %>
    </label>
  </li>
  <li>
    <input type="checkbox" id="filter-power-switch"
        data-filter-value="power" />
    <label for="filter-power-switch">
      Power
      <%= image_tag 'power_pin.png', size: '16x16', alt: 'power' %>
    </label>
  </li>
  <li>
    <input type="checkbox" id="filter-none" data-filter-value="nothing" />
    <label for="filter-none">
      None
      <%= image_tag 'none_pin.png', size: '16x16', alt: 'none' %>
    </label>
  </li>
  <div class="peopleCount">
    <p class="filter-group-label">Min. # of people:</p>
    <div class="range-slider radius" data-filter-value="people"
        data-slider="0" data-options="start: 0; end: 500; step: 10; display_selector: #peopleCountNumber;">
      <span class="range-slider-handle" role="slider" tabindex="0"></span>
      <span class="range-slider-active-segment"></span>
      <input type="hidden">
    </div>
    <p id="peopleCountNumber"></p>
  </div>
</ul>

app/views/session/new.html.erb
<h2>Sign in</h2>

<% if @redirect_url %>
<p>
  We need you to sign in before we can show you the page that you are trying to
  view.
</p>
<% end %>

<div class="login">
<%= form_for @session, url: session_path,
                       builder: FoundationFormBuilder::Icons do |f| %>

  <%= f.email_field :email, autofocus: true, required: true,
          placeholder: 'your@email.com',
          label: { icon: fa_icon('at'), text: 'Email Address' }  %>

  <%= f.password_field :password, required: true,
          placeholder: 'your password',
          label: { icon: fa_icon('key'), text: 'Password' }  %>

  <div class="row">
    <div class="small-5 small-offset-1 columns">
      <%= button_tag name: 'login', value: 'requested', type: 'submit',
                     class: 'large success button expand' do %>
        <%= fa_icon 'sign-in' %> Sign in
      <% end %>
    </div>
    <div class="small-5 columns">
      <%= button_tag name: 'reset_password', value: 'requested',
                     type: 'submit', formaction: reset_password_session_path,
                     class: 'large button expand' do %>
        <%= fa_icon :unlock %> Reset password
      <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/session/password_change.html.erb
<h2>Password Change</h2>

<% if @credential.updated_at %>
<p class="password_age_notice">
  Your have been using the same password for
  <span class="password_age">
    <%= time_ago_in_words @credential.updated_at, include_seconds: true %>.
  </span>
</p>
<% end %>

<%= form_for @credential, url: change_password_session_path,
      as: :credential, method: :post,
      builder: FoundationFormBuilder::Icons do |f| %>

  <% unless @credential.new_record? %>
  <%= f.password_field :old_password, required: true,
          placeholder: 'your current password',
          label: { icon: fa_icon('key'), text: 'Current Password' }  %>
  <% end %>

  <%= f.password_field :password, required: true,
          placeholder: 'a new clever password',
          label: { icon: fa_icon('key'), text: 'New Password' }  %>

  <%= f.password_field :password_confirmation, required: true,
          placeholder: 'same new clever password',
          label: { icon: fa_icon('key'), text: 'Confirm New Password' }  %>

  <div class="row">
    <div class="small-11 small-offset-1 columns">
      <%= f.button name: 'login', value: 'requested',
                   class: 'large success button expand' do %>
        <%= fa_icon :save %> Change Password
      <% end %>
    </div>
  </div>
<% end %>

app/views/session/welcome.html.erb
<section class="login-controls">
  <div class="row text-center">
    <p>
      <%= link_to '/auth/google', class: 'large round success button' do %>
        <%= fa_icon :google %> Sign in with Google
      <% end %>
      or
    </p>
    <p>
      <%= link_to new_session_path, class: 'large round button' do %>
        <%= fa_icon :key %> Sign in with password
      <% end %>
      or
      <%= link_to 'Sign Up', new_user_path, class: 'large round success button' %>
    </p>
  </div>
</section>