config/routes.rb
Rails.application.routes.draw do
  root to: 'session#show'

  authpwn_session

  get 'venues' => 'venues#index'
  post 'venues/:id/add_warning' => 'venues#add_warning'

  resources :users

  get 'legal/:document' => 'legal#show', as: :legal
  get 'legal' => 'legal#show'

end

app/views/layouts/_footer_nav.html.erb
<div class="row">
  <ul class="inline-list" id="footer-nav">
    <% if false %>
    <li>
      <%= link_to 'About', about_path(document: :about) %>
    </li>
    <li>
      <%= link_to 'Team', about_path(document: :team) %>
    </li>
    <% end %>
    <li>
      Sanctuary &copy; 2015
    </li>
    <li>
      <%= link_to 'Terms', legal_path(document: :tos) %>
    </li>
    <li>
      <%= link_to 'Privacy', legal_path(document: :privacy) %>
    </li>
    <li>
      <%= link_to 'DMCA', legal_path(document: :dmca) %>
    </li>
  </ul>
</div>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58078874-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_top_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to root_url do %>
          <%= fa_icon :home %> Sanctuary
        <% end %>
      </h1>
    </li>
  </ul>
  <% if current_user %>
  <section class="top-bar-section">
    <ul class="right">
      <li class="has-dropdown">
        <a>
          <%= fa_icon :user %>

          <%= current_user.name || current_user.email %>
        </a>
        <ul class="dropdown">
          <% if current_user.password_credential %>
          <li>
            <%= link_to session_change_password_path do %>
              <%= fa_icon :key %> Change Password
            <% end %>
          </li>
          <% end %>
          <li>
            <%= link_to session_path, method: :delete do %>
              <%= fa_icon :'sign-out' %> Sign Out
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </section>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Sanctuary</title>

  <%= stylesheet_link_tag :application %>
  <%= render 'layouts/google_analytics' %>
  <%= javascript_include_tag 'vendor/modernizr' %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>

<body>

<header id="header">
  <%= render 'layouts/top_nav' %>
</header>

<article id="page-body">
<% if flash[:notice] %>
<p data-alert id="flash-notice-box">
  <%= flash[:notice] %>
  <a href="#" title="Close" class="close">&times;</a>
</p>
<% end %>
<% if flash[:alert] %>
<p data-alert id="flash-alert-box">
  <%= flash[:alert] %>
  <a href="#" title="Close" class="close">&times;</a>
</p>
<% end %>

<%= yield %>
</article>

<footer id="footer">
  <%= render 'layouts/footer_nav' %>
</footer>

<%= javascript_include_tag :application %>
<%= google_maps_include_tag %>
</body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html lang="en" class="map">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Sanctuary</title>

  <%= stylesheet_link_tag :application %>
  <%= render 'layouts/google_analytics' %>
  <%= javascript_include_tag 'vendor/modernizr' %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>

<body>

<header id="header">
  <%= render 'layouts/top_nav' %>
</header>

<article id="page-body">
<%= yield %>
</article>

<%= javascript_include_tag :application %>
<%= google_maps_include_tag %>
</body>
</html>

app/views/layouts/web_welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Sanctuary</title>

  <%= stylesheet_link_tag :application %>
  <%= render 'layouts/google_analytics' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>

<body>

<article id="page-body">
<% if flash[:notice] %>
<p data-alert id="flash-notice-box">
  <%= flash[:notice] %>
  <a href="#" title="Close" class="close">&times;</a>
</p>
<% end %>
<% if flash[:alert] %>
<p data-alert id="flash-alert-box">
  <%= flash[:alert] %>
  <a href="#" title="Close" class="close">&times;</a>
</p>
<% end %>

<%= yield %>
</article>

<footer id="footer">
  <%= render 'layouts/footer_nav' %>
</footer>

<%= javascript_include_tag :application %>
</body>
</html>